name: Build package

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - '**.py'
      - '.github/workflows/build_package.yml'
      - 'pyproject.toml'
      - 'requirements.txt'

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install build
        run: python -m pip install -U build
      - name: Build package
        run: python -m build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          overwrite: true
          retention-days: 2
