name: mypy check

on:
  push:
    paths:
      - 'jester/**.py'
      - '.github/workflows/mypy_check.yml'
      - 'mypy.ini'
      - 'requirements.txt'

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          architecture: x64
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'mypy'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
